### ISSUE TITLE
Need more robust handling when defining foreignKey/foreignCollection by string

### ISSUE THREAD

**Issue by ggoodwin37** [fritzy/Dulcimer#28]
I tried to define foreignKey/foreignCollection relationships in a model, using a string for the foreign type. This did not end well. Either I used the wrong string (the strings matched the name fields of the other models), or I used the right string but Dulcimer didn't handle it correctly. Either way, I ended up with a less-than-helpful error stack from code that wasn't immediately related to the problematic foreignKey.

I was able to get around the issue by passing a Factory ref instead of a string to describe the foreign model type.

Here's an example of the stack I saw:

/Users/gideong/local/rn/node_modules/dulcimer/lib/foreign.js:65
                               var fbucket = [bucket[0], fmodel.options.name];
                                                                       ^
TypeError: Cannot read property 'name' of undefined
    at async.each.obj.(anonymous function) (/Users/gideong/local/rn/node_modules/dulcimer/lib/foreign.js:65:77)
    at /Users/gideong/local/rn/node_modules/dulcimer/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/Users/gideong/local/rn/node_modules/dulcimer/node_modules/async/lib/async.js:32:24)
    at Object.async.each (/Users/gideong/local/rn/node_modules/dulcimer/node_modules/async/lib/async.js:110:9)
    at /Users/gideong/local/rn/node_modules/dulcimer/lib/foreign.js:62:39
    at /Users/gideong/local/rn/node_modules/dulcimer/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/Users/gideong/local/rn/node_modules/dulcimer/node_modules/async/lib/async.js:32:24)
    at Object.async.each (/Users/gideong/local/rn/node_modules/dulcimer/node_modules/async/lib/async.js:110:9)
    at /Users/gideong/local/rn/node_modules/dulcimer/lib/foreign.js:58:31
    at fn (/Users/gideong/local/rn/node_modules/dulcimer/node_modules/async/lib/async.js:582:34)
    at Object._onImmediate (/Users/gideong/local/rn/node_modules/dulcimer/node_modules/async/lib/async.js:498:34)
    at processImmediate [as _immediateCallback](timers.js:336:15)

**Comment by fritzy** [comment]
I'm closing out all of the issues on this project. I'm sorry that I didn't help you 5 years ago.
